### ISSUE TITLE
Maintaining a certain speed is not working for reverse direction

### ISSUE THREAD

**Issue by adrcotfas** [pololu/drv8835-motor-shield#1]
Hi,
When I try to keep the maximum speed using delay() and motors.flip are false everything works as expected.
e.g.

```
for (int speed = 0; speed <= 400; speed++)
  {
    motors.setM1Speed(speed);
    motors.setM2Speed(speed); //  or motors.setSpeeds(speed,speed)
    delay(2);
  }

  delay(2000); // here we are running at full speed for 2 seconds

  for (int speed = 400; speed >= 0; speed--)
  {
    motors.setM1Speed(speed);
    motors.setM2Speed(speed);
    delay(2);
  }
```

When I try to do the same in reverted direction (flipping the motors or using negative speeds from 0 to -400), during the delay time the motors do not move. I would expect them to run at the maximum speed as for the non-flipped example.

How can I fix this?
Thank you!

P.S.
I'm using this library with two DRV8838 connected accordingly.
It's working just fine if I try it with the provided example - one motor at a time. But I need this for both motors.

**Comment by DavidEGrayson** [comment]
The more appropriate place for this type of discussion would be the Pololu forum, and I see you have already started a thread there:

http://forum.pololu.com/viewtopic.php?f=15&t=9751

We use GitHub issues to discuss bugs in the code.

**Comment by adrcotfas** [comment]
That's what I assumed by opening the issue (a bug in the code).
